import Head from 'next/head'
import Navbar from '../components/Navbar'
import Slider from '../components/Slider'

export async function getStaticProps(){
  const bgImages = await fetch("https://63189f2cf6b281877c71eab0.mockapi.io/slider").then(res => res.json());
  return{
    props: {
      bgImages
    }
  }
}
export default function Home({bgImages}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Slider bgImages={bgImages}/>
    </div>
  )
}
